export const ForgotPasswordActionTypes = {
    SEND_PASSWORD_REST_EMAIL_FIRST: '@@auth/SEND_PASSWORD_REST_EMAIL_FIRST',
    SEND_PASSWORD_REST_EMAIL_LOADING: '@@auth/SEND_PASSWORD_REST_EMAIL_LOADING',
    SEND_PASSWORD_REST_EMAIL_SUCCESS: '@@auth/SEND_PASSWORD_REST_EMAIL_SUCCESS',
    SEND_PASSWORD_REST_EMAIL_ERROR: '@@auth/SEND_PASSWORD_REST_EMAIL_ERROR',
    SEND_PASSWORD_REST_EMAIL_RESET: '@@auth/SEND_PASSWORD_REST_EMAIL_RESET',
};

