import { CheckSquare, Clock, AlertCircle, CheckCircle2, Filter } from 'lucide-react';
import { Badge } from '../../ui/badge';

export function ActionItemsContent() {
  const actionItems = [
    {
      id: 1,
      title: 'Replace broken lamp in bedroom',
      property: 'Sunset Beach Villa',
      status: 'Open',
      priority: 'High',
      dueDate: 'Today',
      assignedTo: 'Maintenance Team',
      createdBy: 'AI'
    },
    {
      id: 2,
      title: 'Restock coffee supplies',
      property: 'Mountain View Retreat',
      status: 'In Progress',
      priority: 'Medium',
      dueDate: 'Tomorrow',
      assignedTo: 'Housekeeping',
      createdBy: 'AI'
    },
    {
      id: 3,
      title: 'Send checkout reminder to guest',
      property: 'Downtown Loft',
      status: 'Complete',
      priority: 'Low',
      dueDate: 'Today',
      assignedTo: 'Auto',
      createdBy: 'AI'
    },
    {
      id: 4,
      title: 'Check pool heating system',
      property: 'Luxury Desert Oasis',
      status: 'Open',
      priority: 'High',
      dueDate: 'Dec 16',
      assignedTo: 'Maintenance Team',
      createdBy: 'Manual'
    },
  ];

  return (
    <>
      {/* Page Header */}
      <div className="px-6 py-5 border-b border-slate-800">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h1 className="text-white text-2xl mb-1">Action Items</h1>
            <p className="text-slate-400">Track and manage operational tasks generated by AI</p>
          </div>
          <div className="flex items-center gap-2">
            <select className="bg-slate-800 border border-slate-700 rounded-lg px-3 py-2 text-slate-300 text-sm focus:outline-none focus:border-blue-500">
              <option>All Properties</option>
              <option>Sunset Beach Villa</option>
              <option>Mountain View Retreat</option>
            </select>
            <button className="px-3 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg text-sm flex items-center gap-2 border border-slate-700 transition-colors">
              <Filter className="w-4 h-4" />
              Filters
            </button>
          </div>
        </div>
      </div>

      {/* Stats */}
      <div className="px-6 py-4 border-b border-slate-800 bg-slate-900/30">
        <div className="grid grid-cols-4 gap-4">
          <div className="bg-slate-800/50 border border-slate-700 rounded-lg p-3">
            <p className="text-slate-400 text-sm mb-1">Open</p>
            <p className="text-white text-2xl">2</p>
          </div>
          <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-3">
            <p className="text-blue-400 text-sm mb-1">In Progress</p>
            <p className="text-white text-2xl">1</p>
          </div>
          <div className="bg-green-500/10 border border-green-500/20 rounded-lg p-3">
            <p className="text-green-400 text-sm mb-1">Complete</p>
            <p className="text-white text-2xl">1</p>
          </div>
          <div className="bg-purple-500/10 border border-purple-500/20 rounded-lg p-3">
            <p className="text-purple-400 text-sm mb-1">AI Generated</p>
            <p className="text-white text-2xl">3</p>
          </div>
        </div>
      </div>

      {/* Action Items List */}
      <div className="p-6">
        <div className="space-y-3">
          {actionItems.map((item) => (
            <div
              key={item.id}
              className="bg-slate-800/50 border border-slate-700 rounded-lg p-5 hover:bg-slate-800 transition-colors"
            >
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-start gap-3 flex-1">
                  <div className="mt-1">
                    {item.status === 'Complete' ? (
                      <CheckCircle2 className="w-5 h-5 text-green-400" />
                    ) : (
                      <div className="w-5 h-5 border-2 border-slate-600 rounded"></div>
                    )}
                  </div>
                  <div className="flex-1">
                    <h3 className="text-white mb-2">{item.title}</h3>
                    <div className="flex items-center gap-3 flex-wrap text-sm">
                      <span className="text-slate-400">{item.property}</span>
                      <span className="text-slate-600">•</span>
                      <div className="flex items-center gap-1.5 text-slate-400">
                        <Clock className="w-3.5 h-3.5" />
                        <span>Due {item.dueDate}</span>
                      </div>
                      <span className="text-slate-600">•</span>
                      <span className="text-slate-400">Assigned to {item.assignedTo}</span>
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  {item.createdBy === 'AI' && (
                    <Badge className="bg-purple-500/10 text-purple-400 border-purple-500/20 text-xs">
                      AI Generated
                    </Badge>
                  )}
                  {item.status === 'Open' && (
                    <Badge className="bg-amber-500/10 text-amber-400 border-amber-500/20">
                      Open
                    </Badge>
                  )}
                  {item.status === 'In Progress' && (
                    <Badge className="bg-blue-500/10 text-blue-400 border-blue-500/20">
                      In Progress
                    </Badge>
                  )}
                  {item.status === 'Complete' && (
                    <Badge className="bg-green-500/10 text-green-400 border-green-500/20">
                      Complete
                    </Badge>
                  )}
                  {item.priority === 'High' && (
                    <Badge className="bg-red-500/10 text-red-400 border-red-500/20">
                      <AlertCircle className="w-3 h-3 mr-1" />
                      High
                    </Badge>
                  )}
                </div>
              </div>
              <div className="flex gap-2">
                {item.status !== 'Complete' && (
                  <>
                    <button className="px-3 py-1.5 bg-green-600/10 hover:bg-green-600/20 text-green-400 rounded-lg text-sm border border-green-500/20 transition-colors">
                      Mark Complete
                    </button>
                    <button className="px-3 py-1.5 bg-slate-700 hover:bg-slate-600 text-slate-300 rounded-lg text-sm border border-slate-600 transition-colors">
                      Reassign
                    </button>
                  </>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
