export const AddPropertiesActionTypes = {
    TESTING_API_FIRST: '@@auth/TESTING_API_FIRST',
    TESTING_API_LOADING: '@@auth/TESTING_API_LOADING',
    TESTING_API_SUCCESS: '@@auth/TESTING_API_SUCCESS',
    TESTING_API_ERROR: '@@auth/TESTING_API_ERROR',
    TESTING_API_RESET: '@@auth/TESTING_API_RESET',

    GO_TO_BILLING_PORTAL_POST_FIRST: '@@auth/GO_TO_BILLING_PORTAL_POST_FIRST',
    GO_TO_BILLING_PORTAL_POST_LOADING: '@@auth/GO_TO_BILLING_PORTAL_POST_LOADING',
    GO_TO_BILLING_PORTAL_POST_SUCCESS: '@@auth/GO_TO_BILLING_PORTAL_POST_SUCCESS',
    GO_TO_BILLING_PORTAL_POST_ERROR: '@@auth/GO_TO_BILLING_PORTAL_POST_ERROR',
    GO_TO_BILLING_PORTAL_POST_RESET: '@@auth/GO_TO_BILLING_PORTAL_POST_RESET',

    POST_PROPERTIES_FIRST: '@@auth/POST_PROPERTIES_FIRST',
    POST_PROPERTIES_LOADING: '@@auth/POST_PROPERTIES_LOADING',
    POST_PROPERTIES_SUCCESS: '@@auth/POST_PROPERTIES_SUCCESS',
    POST_PROPERTIES_ERROR: '@@auth/POST_PROPERTIES_ERROR',
    POST_PROPERTIES_RESET: '@@auth/POST_PROPERTIES_RESET',

    GET_QUESTIONNAIRE_FIRST: '@@auth/GET_QUESTIONNAIRE_FIRST',
    GET_QUESTIONNAIRE_LOADING: '@@auth/GET_QUESTIONNAIRE_LOADING',
    GET_QUESTIONNAIRE_SUCCESS: '@@auth/GET_QUESTIONNAIRE_SUCCESS',
    GET_QUESTIONNAIRE_ERROR: '@@auth/GET_QUESTIONNAIRE_ERROR',
    GET_QUESTIONNAIRE_RESET: '@@auth/GET_QUESTIONNAIRE_RESET',

    UPDATE_QUESTIONNAIRE_FIRST: '@@auth/UPDATE_QUESTIONNAIRE_FIRST',
    UPDATE_QUESTIONNAIRE_LOADING: '@@auth/UPDATE_QUESTIONNAIRE_LOADING',
    UPDATE_QUESTIONNAIRE_SUCCESS: '@@auth/UPDATE_QUESTIONNAIRE_SUCCESS',
    UPDATE_QUESTIONNAIRE_ERROR: '@@auth/UPDATE_QUESTIONNAIRE_ERROR',
    UPDATE_QUESTIONNAIRE_RESET: '@@auth/UPDATE_QUESTIONNAIRE_RESET',

};
