export const PagesApisActionTypes = {
    GET_USER_DATA_FIRST: '@@auth/GET_USER_DATA_FIRST',
    GET_USER_DATA_LOADING: '@@auth/GET_USER_DATA_LOADING',
    GET_USER_DATA_SUCCESS: '@@auth/GET_USER_DATA_SUCCESS',
    GET_USER_DATA_ERROR: '@@auth/GET_USER_DATA_ERROR',
    GET_USER_DATA_RESET: '@@auth/GET_USER_DATA_RESET',
};
