export const PagesApisActionTypes = {
    GET_USER_DATA_FIRST: '@@auth/GET_USER_DATA_FIRST',
    GET_USER_DATA_LOADING: '@@auth/GET_USER_DATA_LOADING',
    GET_USER_DATA_SUCCESS: '@@auth/GET_USER_DATA_SUCCESS',
    GET_USER_DATA_ERROR: '@@auth/GET_USER_DATA_ERROR',
    GET_USER_DATA_RESET: '@@auth/GET_USER_DATA_RESET',

    POST_CREATE_CHECKOUT_SESSION_FIRST: '@@auth/POST_CREATE_CHECKOUT_SESSION_FIRST',
    POST_CREATE_CHECKOUT_SESSION_LOADING: '@@auth/POST_CREATE_CHECKOUT_SESSION_LOADING',
    POST_CREATE_CHECKOUT_SESSION_SUCCESS: '@@auth/POST_CREATE_CHECKOUT_SESSION_SUCCESS',
    POST_CREATE_CHECKOUT_SESSION_ERROR: '@@auth/POST_CREATE_CHECKOUT_SESSION_ERROR',
    POST_CREATE_CHECKOUT_SESSION_RESET: '@@auth/POST_CREATE_CHECKOUT_SESSION_RESET',

    UPDATE_ACCOUNT_INFO_FIRST: '@@auth/UPDATE_ACCOUNT_INFO_FIRST',
    UPDATE_ACCOUNT_INFO_LOADING: '@@auth/UPDATE_ACCOUNT_INFO  _LOADING',
    UPDATE_ACCOUNT_INFO_SUCCESS: '@@auth/UPDATE_ACCOUNT_INFO  _SUCCESS',
    UPDATE_ACCOUNT_INFO_ERROR: '@@auth/UPDATE_ACCOUNT_INFO_ERROR',
    UPDATE_ACCOUNT_INFO_RESET: '@@auth/UPDATE_ACCOUNT_INFO_RESET',
};
