const Data = [
  {
    title: "Inquiries",
    description: "Equipped with details about your properties, HostBuddy can answer guest inquiries and provide information about your listings. HostBuddy can communicate in any language, right out of the box.",
    messages: [
      {
        text: "Hallo Was kann man machen in zermatt zu dieser Zeit? Ist die Wohnung zentral gelegen? Kann man Skifahren in Zermatt und wo kann ich mieten? Hat die Wohnung eine Waschmaschine? Danke für eine Antwort",
        translatedText: "Hello, what can one do in Zermatt at this time? Is the apartment centrally located? Can you ski in Zermatt and where can I rent? Does the apartment have a washing machine? Thanks for an answer",
        sender: "guest",
        timeDate: "9/27 4:56 PM",
        sendBy: "Guest",
      },
      {
        text: "Hallo! Ja, die Wohnung ist sehr zentral gelegen, nur 4 Gehminuten vom Sunnegga Express entfernt. Zermatt bietet ganzjährig Gletscherskifahren, aber die Hauptskisaison beginnt normalerweise Ende November. Es gibt mehrere Skiverleihgeschäfte in der Stadt. Die Wohnung ist mit einer Waschmaschine ausgestattet. Zermatt bietet viele Aktivitäten wie Wandern, Mountainbiken und Sightseeing. Wenn Sie weitere Informationen benötigen, fragen Sie gerne!",
        translatedText: "Hello! Yes, the apartment is very centrally located, just a 4-minute walk from the Sunnegga Express. Zermatt offers year-round glacier skiing, but the main ski season usually starts at the end of November. There are several ski rental shops in town. The apartment is equipped with a washing machine. Zermatt offers many activities such as hiking, mountain biking, and sightseeing. If you need more information, feel free to ask!",
        sender: "host",
        timeDate: "9/27 4:57 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "Was macht diese Wohnung speziell? Gibt es etwas zu beachten wenn man nach zermatt reist? Wir sind eine Familie mit Grosseltern und Kinder. Ist die Unterkunft einfach zugänglich? Gibt es ein Babybett in der Unterkunft?",
        translatedText: "What makes this apartment special? Is there anything to consider when traveling to Zermatt? We are a family with grandparents and children. Is the accommodation easily accessible? Is there a baby cot in the accommodation?",
        sender: "guest",
        timeDate: "9/27 4:58 PM",
        sendBy: "Guest",
      },
      {
        text: "Die Wohnung besticht durch ihren Matterhorn-Blick und zentrale Lage! Wichtig zu wissen: Zermatt ist autofrei, und die Wohnung ist über 115 Stufen erreichbar - das könnte für Großeltern herausfordernd sein. Ein Reisebettchen für Babys ist vorhanden. Die Wohnung bietet viel Platz für Familien, aber bitte bedenken Sie die Zugänglichkeit. Haben Sie noch Fragen zur Unterkunft oder Ihrer Reise nach Zermatt?",
        translatedText: "The apartment impresses with its Matterhorn view and central location! Important to know: Zermatt is car-free, and the apartment is accessible via 115 steps - this could be challenging for grandparents. A travel cot for babies is available. The apartment offers plenty of space for families, but please consider the accessibility. Do you have any other questions about the accommodation or your trip to Zermatt?",
        sender: "host",
        timeDate: "9/27 4:59 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "wie genau kommen wir mit dem Auto zur WOhnung?",
        translatedText: "How exactly do we get to the apartment by car?",
        sender: "guest",
        timeDate: "9/27 5:00 PM",
        sendBy: "Guest",
      },
      {
        text: "Guten Tag! Zermatt ist eine autofreie Stadt. Sie müssen Ihr Auto in Täsch parken und von dort einen 12-minütigen Shuttle-Zug nach Zermatt nehmen. In Zermatt können Sie dann ein Elektrotaxi zur Wohnung nehmen. Benötigen Sie weitere Informationen zur Anreise?",
        translatedText: "Good day! Zermatt is a car-free town. You have to park your car in Täsch and take a 12-minute shuttle train from there to Zermatt. In Zermatt, you can then take an electric taxi to the apartment. Do you need more information about the arrival?",
        sender: "host",
        timeDate: "9/27 5:01 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "Können sie mir ein Taxi Firma empfehlen bitte",
        translatedText: "Can you recommend a taxi company to me, please?",
        sender: "guest",
        timeDate: "9/27 5:02 PM",
        sendBy: "Guest",
      },
      {
        text: "In Zermatt finden Sie elektrische Taxis direkt am Bahnhof. Bitten Sie den Fahrer einfach, Sie zum Belmont House, Wiestistrasse 210, zu bringen. Die Taxis sind leicht zu finden und eine bequeme Option für Ihre Familie!",
        translatedText: "In Zermatt, you will find electric taxis directly at the train station. Just ask the driver to take you to Belmont House, Wiestistrasse 210. The taxis are easy to find and a convenient option for your family!",
        sender: "host",
        timeDate: "9/27 5:01 PM",
        sendBy: "HostBuddy",
      },
    ],
  },
  {
    title: "2Issue Troubleshooting",
    description: "2Hostbuddy can intelligently troubleshoot issues on your behalf based on the property information you provide it.",
    messages: [
      {
        text: "Hi there! What can I assist you with today?",
        sender: "guest",
        timeDate: "9/27 5:03 PM",
        sendBy: "Guest",
      },
      {
        text: "I want to know more about your services.",
        sender: "host",
        timeDate: "9/27 5:04 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "We offer a variety of services including account management, support, and personalized recommendations. What are you specifically interested in?",
        sender: "guest",
        timeDate: "9/27 5:05 PM",
        sendBy: "Guest",
      },
      {
        text: "I’m interested in account management. Can you explain how it works?",
        sender: "host",
        timeDate: "9/27 5:06 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "Of course! Our account management service allows you to easily track your account activities, update your information, and manage your preferences. Would you like to sign up?",
        sender: "guest",
        timeDate: "9/27 5:07 PM",
        sendBy: "Guest",
      },
      {
        text: "Yes, please sign me up for that service.",
        sender: "host",
        timeDate: "9/27 5:08 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "Great! I’ve signed you up. You can start using it right away. Let me know if you have any questions!",
        sender: "guest",
        timeDate: "9/27 5:09 PM",
        sendBy: "Guest",
      },
    ],
  },
  {
    title: "3Issue Troubleshooting",
    description: "3Hostbuddy can intelligently troubleshoot issues on your behalf based on the property information you provide it.",
    messages: [
      {
        text: "Good day! How can I assist you today?",
        sender: "guest",
        timeDate: "9/27 5:10 PM",
        sendBy: "Guest",
      },
      {
        text: "I need help with my billing.",
        sender: "host",
        timeDate: "9/27 5:11 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "Sure! What specific billing issue are you facing?",
        sender: "guest",
        timeDate: "9/27 5:12 PM",
        sendBy: "Guest",
      },
      {
        text: "I was charged twice this month.",
        sender: "host",
        timeDate: "9/27 5:13 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "I apologize for the inconvenience. Let me check that for you.",
        sender: "guest",
        timeDate: "9/27 5:14 PM",
        sendBy: "Guest",
      },
      {
        text: "Thank you! I appreciate it.",
        sender: "host",
        timeDate: "9/27 5:15 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "It seems there was a system error. I will issue a refund for the extra charge. You should see it in your account within 3-5 business days.",
        sender: "guest",
        timeDate: "9/27 5:16 PM",
        sendBy: "Guest",
      },
    ],
  },
  {
    title: "4Issue Troubleshooting",
    description: "4Hostbuddy can intelligently troubleshoot issues on your behalf based on the property information you provide it.",
    messages: [
      {
        text: "Hello! How can I help you today?",
        sender: "guest",
        timeDate: "9/27 5:17 PM",
        sendBy: "Guest",
      },
      {
        text: "I want to change my account settings.",
        sender: "host",
        timeDate: "9/27 5:18 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "What specific settings would you like to change?",
        sender: "guest",
        timeDate: "9/27 5:19 PM",
        sendBy: "Guest",
      },
      {
        text: "I want to update my password.",
        sender: "host",
        timeDate: "9/27 5:20 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "Please provide your current password and the new password you'd like to set.",
        sender: "guest",
        timeDate: "9/27 5:21 PM",
        sendBy: "Guest",
      },
      {
        text: "My current password is 'currentPass123' and my new password will be 'newPass456'.",
        sender: "host",
        timeDate: "9/27 5:22 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "Your password has been updated successfully. Is there anything else you need help with?",
        sender: "guest",
        timeDate: "9/27 5:23 PM",
        sendBy: "Guest",
      },
    ],
  },
  {
    title: "5Issue Troubleshooting",
    description: "5Hostbuddy can intelligently troubleshoot issues on your behalf based on the property information you provide it.",
    messages: [
      {
        text: "Hi! What assistance do you need today?",
        sender: "guest",
        timeDate: "9/27 5:24 PM",
        sendBy: "Guest",
      },
      {
        text: "I want to report a bug in the application.",
        sender: "host",
        timeDate: "9/27 5:25 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "I'm sorry to hear that. Can you please describe the issue?",
        sender: "guest",
        timeDate: "9/27 5:26 PM",
        sendBy: "Guest",
      },
      {
        text: "The app crashes every time I try to open it.",
        translatedText: "I am stupid and I don't know how to use the app.",
        sender: "host",
        timeDate: "9/27 5:27 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "Thank you for the information. I'll forward this to our technical team immediately.",
        translatedText: "It's too early for this lemme make my tech nerts deal with you.",
        sender: "guest",
        timeDate: "9/27 5:28 PM",
        sendBy: "Guest",
      },
      {
        text: "I hope it gets fixed soon. Thank you!",
        sender: "host",
        timeDate: "9/27 5:29 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "You're welcome! We'll keep you updated on the progress.",
        sender: "guest",
        timeDate: "9/27 5:30 PM",
        sendBy: "Guest",
      },
    ],
  },
  {
    title: "6Issue Troubleshooting",
    description: "6Hostbuddy can intelligently troubleshoot issues on your behalf based on the property information you provide it.",
    messages: [
      {
        text: "Good evening! How can I assist you today?",
        sender: "guest",
        timeDate: "9/27 5:31 PM",
        sendBy: "Guest",
      },
      {
        text: "Can you recommend a product for me?",
        translatedText: "duhhhh idk what to buy",
        sender: "host",
        timeDate: "9/27 5:32 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "I'd like to hear your thoughts.",
        sender: "host",
        timeDate: "9/27 5:32 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "Of course! What type of product are you looking for?",
        sender: "guest",
        timeDate: "9/27 5:33 PM",
        sendBy: "Guest",
      },
      {
        text: "I'm looking for a new laptop.",
        sender: "host",
        timeDate: "9/27 5:34 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "I recommend the XYZ laptop. It's powerful and perfect for both work and gaming!",
        sender: "guest",
        timeDate: "9/27 5:35 PM",
        sendBy: "Guest",
      },
      {
        text: "That sounds great! What are its key features?",
        sender: "host",
        timeDate: "9/27 5:36 PM",
        sendBy: "HostBuddy",
      },
      {
        text: "It has a high-resolution display, fast processing power, and long battery life. Would you like to know more?",
        sender: "guest",
        timeDate: "9/27 5:37 PM",
        sendBy: "Guest",
      },
    ],
  },
];

export default Data;
